---
- name: install tomcat using get url 
  get_url: 
    url: "{{ tomcat_url}}"
    dest: /opt
- name: extract the tar/zip file
  unarchive: 
     src: /opt/{{ appname }}-{{ version }}.tar.gz
     dest: /opt
     remote_src: yes

- name: rename the  apache-tomact  directory 
  stat: 
    path: /opt/tomcat
  register: drcheck  
  
- debug: 
    var: drcheck  

- name: if directory is available skip 
  command: 
     chdir: /opt
     cmd:  mv  {{ appname }}-{{ version }}  tomcat
  when: drcheck.stat.exists == false
  












